# Generated by Django 5.0.6 on 2024-06-23 08:20

import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'ordering': ['-publish'], 'verbose_name': 'اطلاعات جدید', 'verbose_name_plural': 'اطلاعات جدید'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelManagers(
            name='costumer',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='PB', max_length=2, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['-publish'], name='gym_costume_publish_7a7b9d_idx'),
        ),
    ]
