# Generated by Django 5.0.6 on 2024-06-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_costumer_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='costumer',
            managers=[
            ],
        ),
    ]
