# Generated by Django 5.0.6 on 2024-06-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='category',
            field=models.CharField(choices=[('برنامه غذایی', 'برنامه غذایی'), ('برنامه ورزشی', 'برنامه ورزشی'), ('این بادی', 'این بادی'), ('اطلاعات پرداخت', 'اطلاعات پرداخت'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
